sample_data:
  min_sample: # < min_sample
    max_files: 10000
  
  medium_sample: # min_sample between medium_sample
    max_files: 100000
    percent: 0.2
  
  many_sample: # medium_sample between many_sample
    max_files: 1000000
    percent: 0.05
  
  too_much_sample: # > many_sample
    percent: 0.01

preprocessing_outlier_rules:
  filter_percent: 1 # % < filter_percent
  impute_percent: 5 # % < impute_percent
  transform_percent: 5 # % > transform_percent
  flag_percent: 10 # % > flag_percent

