sampling: # if not value given 'random' will be used
representative_column: #use when "representative" is selected

null_num_handler: # if not value given 'mean' will be used
null_cat_handler: # if not value given 'constantValue' will be used
null_cat_handler_value: # if not value is given "Unknown" will be used

null_general_values: 
  null_impute_numerics: # if None -> the median will be used if nulls are found
  null_impute_categorics: # if None -> the mode will be used if nulls are found

distribution: 
  enable: True
  transformer: 

outlier: 
  enable: True
  strategy: # if not given "iqr" will be the strategy used
  filter: 
  impute_outliers: 
  flag: # Bool True/False
  transform: 

correlation:
  enable: True
  high_correlation: # if None, then join will be the operation
  remove_column: # just if high_correlation is selected if not, join will be the auto operation for not deleting any column

category: # THIS IS MISSING
  enable: 
  operation: # if not value given, "Group" operation will be given
  name_operation_value: # Value for operation, if None, then "Unknown" will be the auto value given
