outlier_decision_maker: 
  scaler: 
    robust_scaler_percent: 5.0
    standard_scaler_percent: 1.0
    # The difference between robust and standard will be MinMaxScaler
  
  filter: 
    none: 10.0
    trim: 2.0
    # The difference betwwen robust and standard will be Capping
  
  impute:
    none: 5.0
    # Less of None will impute with median
  
  flag: 
    flag_true: 5.0
    # Less flag_true will be False
  
  transform: 
    log1p: 100.0 # just positive will be sqrt
    # else will be None

correlation_decision_maker: 
  sampling: 
    percent: 30.0 
    method: 'random'
    representative_columns: # if None is the value, then the sample_percent will be random data
  # if a str or list is given, the sample_percent will be the data in this representative columns
  
  handle_nulls: 'median'
  threshold: 75.0 # multicollinearity value to filter columns with >= threshold 

category_decision_maker: 
  rare_threshold_limit: 10 #Limit of count rare values


