path: 
  data: 'games.csv'
  sample_data_percent: 0.1 #percent data analysis, this can change by system to be optimal

eda: 
  general_information: True
  null_values: True
  null_values_percent_column: 0.65
  null_values_percent_row: 0.40
  basic_analysis_data: 
    distribution: 
      columns: 
      enable: True
    outliers: 
      columns:
      enable: True
      method: #if a method is not given, the value will be 'iqr'
    correlation: 
      columns: 
      enable: True
    category_dominance: 
      columns: 
      enable: True
      top_n: #if a top_n is not given, the value will be 2
      rare_threshold_percent: #if a threshold is not given, the value will be 0.01









