defaults: 
  - eda_threshold: eda_threshold
  - cleaning: cleaning_threshold
  - preprocessing: preprocessing_threshold
  - modeling: modeling_threshold
  
  - data: 'Churn'
  - model: 
    - 'RandomForestRegressor'
    - 'LinearRegressor'
    - 'RandomForestClassifier'
  
  - _self_

data_management: 
  output:
    clean_data: 
      enable: False
      name: 
    preprocessing_data: 
      enable: False
      name: 
  
  data_protection: 
    enable: True
    method: 'permutation_matrix'
    delete_original_after: True
  
  overhead_percent: 1.8
  sample_data_percent: 0.1 #percent data analysis, this can change by system to be optimal, not used now, until laz and streaming is added

eda: 
  null_values: True
  null_values_percent_column: 0.65
  null_values_percent_row: 0.40
  basic_analysis_data: 
    distribution: 
      columns: 
      enable: True  
    outliers: 
      columns:
      enable: True
      method: #if a method is not given, the value will be 'iqr'
    correlation: 
      columns: 
      enable: True
    category_dominance: 
      columns: 
      enable: True
      top_n: #if a top_n is not given, the value will be 2
      rare_threshold_percent: #if a threshold is not given, the value will be 0.01

hydra: 
  run:
    dir: config/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}


