#ml_training: # Encoder & Scaler not working
#  target: Exited
#  
#  train_test_search: 0.25 
#  train_test_final: 0.25 # 🚨 NOT AVAILABLE 🚨
#  random_state: 42
#  
#  encoder: # 🚨 NOT AVAILABLE 🚨 if None=Auto (Rules in config_modeling), if not all columns will have the encoder you selected 
#  scaler: # 🚨 NOT AVAILABLE 🚨 if none, auto will be use, the algorithm will decide
#  scaler_outlier_method: # if none, iqr will be used